build: false

version: 1.0.{build}

platform:
  - x64

environment:
  matrix:
    - PYTHON: 2.7
    - PYTHON: 3.6

init:
  #Uncomment the following line to gain RDP access to an appveyor machine.
  #Login info will appear in the console
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - set CONDA=Miniconda
  - if "%PYTHON%" == "3.6" (set CONDA=Miniconda3)
  - if "%PLATFORM%" == "x64" (set CONDA=%CONDA%-x64)
  - echo %CONDA%
  - set PATH=C:\%CONDA%;C:\%CONDA%\Scripts;%PATH%
  - conda config --set always_yes yes
  # We need to do this first as other commands may not work with older versions of conda.
  - conda update conda
  - conda create -n openconcept python=%PYTHON%
  - activate openconcept
  - conda env update -f=environment.yml
  # - conda install numpy scipy nose hdf5 h5py sphinx mock pip --quiet
  #Grab testflo for running tests, to ensure examples are run
  # - pip install redbaron
  # - pip install git+https://github.com/OpenMDAO/testflo.git
  # - pip install matplotlib
  # #Install openmdao and dependencies
  # - pip install OpenMDAO>=2.3.1
  # - pip install pytest
  # - pip install six
  # - pip install -r requirements_conda.txt
  #Install openconcept
  # - pip install -e .

test_script:
  - python -m pytest

